### PR TITLE
Fix typo

### PR DESCRIPTION
**Pull request by phikal**
Just noticed this while browsing the code.

### CODE REVIEW

**Review by gares — APPROVED** [review]

**Comment by gares** [comment]
please, run make and the push also the coq-builtin.elpi file

**Comment by phikal** [comment]
That doesn't appear to change anything related to this patch, 

One change is 

```diff
-external type declare_constraint variadic any prop.
+external type declare_constraint any -> any -> variadic any prop.
```

and the other one is related to `unix.process.*`.

**Comment by gares** [comment]
This comes from recent elpi

**Comment by phikal** [comment]
Oh, ok I was assuming you were expecting something from the previous commit to propagate into the new commit.

**Comment by gares** [comment]
sorry, I think I mislead you

**Pull request merged**
