### PR TITLE
Nix toolbox update

### PR DESCRIPTION
**Pull request by proux01**

### CODE REVIEW

**Comment by gares** [comment]
amazing

**Comment by gares** [comment]
it is still half broken https://github.com/LPCIC/coq-elpi/pull/726#pullrequestreview-2475825219 but it would be nice if the manual edit I do on the job was propagated to the toolbox, since it has a killer feature: it prints the errors.

**Comment by CohenCyril** [comment]
> There is something wrong happening with the Nix cache @CohenCyril would you have a clue? We get CI errors like
> 
> ```
> Compiled library mathcomp.algebra.ssrnum (in file /nix/store/2zi311i5fx8z96r7a5f6akfb9s32zyd5-coqdev-mathcomp-algebra-dev/lib/coq/dev/user-contrib/mathcomp/algebra/ssrnum.vo)
> makes inconsistent assumptions over library mathcomp.fingroup.fingroup
> ```

I've been banging my head on it for days now...

**Comment by proux01** [comment]
Now testing elpi 2.0.6 with https://github.com/LPCIC/elpi/pull/303

**Comment by proux01** [comment]
Yes, I guess our best course of action is to merge this now and come back to coq-nix-toolbox master in a few days once https://github.com/coq-community/coq-nix-toolbox/pull/302 will be merged.

**Pull request merged**
