### PR TITLE
parse a bunch of Coq keywords as strings (fix #107)

### LINKED ISSUE #107: Binding symbol arguments
Can we add parsing for arbitrary symbols so that
`Elpi foo x := a.`
has arguments `[str ":=", str "a"]` ?

### PR DESCRIPTION
**Pull request by gares**
Nothing obvious missing? @CohenCyril

### CODE REVIEW

**Comment by CohenCyril** [comment]
I can think of many other symbols `+` (used in `Hint Modes`), `/`, `!` (used in `Arguments`) etc...
However `of` is not a keyword, and why is `-` bound to an identifier?

**Comment by gares** [comment]
I wanted to be able to write `foo -x -y -help` (to distinguish arguments from options) but I guess it makes no more sense after #109 .

For the other symbols, I guess I'll try to be more generic next week, that is have a custom parser that accepts any registered symbol and be done with it.

**Comment by gares** [comment]
wrt `of`, it is a keyword to me ;-)
```
Coq < Definition of := 1.
of is defined

Coq < Require Import ssreflect.
[Loading ML file ssrmatching_plugin.cmxs ... done]
[Loading ML file ssreflect_plugin.cmxs ... done]

Coq < Definition of := 1.
Toplevel input, characters 11-13:
> Definition of := 1.
>            ^^
Error:
Syntax error: [Prim.ident_decl] expected after [def_token] (in [vernac:gallina]).
```

**Comment by gares** [comment]
This PR now parses any Coq keyword or symbol (but for `.`) in command mode.

**Pull request merged**
