### PR TITLE
Overlay rm library optim

### PR DESCRIPTION
**Pull request by gares**
@maximedenes

### CODE REVIEW

**Comment by maximedenes** [comment]
Thanks @gares ! You write "overlay", but this is backward-compatible, isn't it?

**Comment by gares** [comment]
Given that there is no release and no users, I guess so but I did not test it.
If CI passes, then I'll merge.

**Comment by maximedenes** [comment]
It failed because of dead code, it seems.

**Comment by maximedenes** [comment]
@gares do you understand what the CI failure is about?

**Comment by gares** [comment]
Looks like I need to rebase this one, I'll do it tomorrow

**Comment by maximedenes** [comment]
Thanks a lot!

**Pull request merged**
