### PR TITLE
Remove/GProj

### PR DESCRIPTION
**Pull request by gares**

### CODE REVIEW

**Comment by maximedenes** [comment]
You may want to merge this in a specific branch that we will track for Coq 8.8.

**Comment by gares** [comment]
the branch `coq-master` is the one tracked by Coq (master).
are you saying we now run CI on something else than master? Like master + v8.8 ?

**Comment by gares** [comment]
ping @maximedenes

**Comment by Zimmi48** [comment]
CI is run on all active branches. From `v8.6` to `master`.
Given that Elpi was recently introduced, it is only tested with `v8.8` and `master`.
You should create a new `coq-v8.8` branch and merge this PR in it.

**Comment by Zimmi48** [comment]
Thanks!

**Pull request merged**
