### PR TITLE
Adapt to coq/coq#15853

### PR DESCRIPTION
**Pull request by proux01**
To be merged synchronously with the upstream PR coq/coq#15853

### CODE REVIEW

**Review by gares — APPROVED** [review]

**Comment by gares** [comment]
Thanks!

**Comment by proux01** [comment]
We may want to give acces to the flag from elpi in the future, but I'm not - yet - skilled enough to do that.

**Comment by gares** [comment]
Well, you are not supposed to do that.

Anyway, for reference a similar commit: https://github.com/LPCIC/coq-elpi/pull/315/commits/08b8133d99ba63a0eca55380d22bc87767d14bdf
In this case I'd add a `@reversible!` and `@non-reversible!` macros to set option `coq:reversible-coercion` to `tt` or `ff` (with the same default of Coq, which I don't know what it is). The `coq.coercion.*` are going to read this from the options, a field of the context (see other builtins reading `local` for example)

**Comment by ana-borges** [comment]
This can now be merged. @gares?

**Pull request merged**
