### PR TITLE
Coercion hook

### PR DESCRIPTION
**Pull request by Tragicus**
Update on the coercion hook on coq-elpi's side, reflecting the changes in Coq (see https://github.com/coq/coq/pull/18236#top).

### CODE REVIEW

**Comment by Tragicus** [comment]
I think the only issue left with this is the naming of the variables used to define the product type used as placeholder for Funclass in apps/coercion/src/coq_elpi_coercion_hook.mlg. Is there a way to generate automatically the name. If not, is there a convention?

**Comment by gares** [comment]
look here https://github.com/coq/coq/blob/970bb08b37f7e05b5b4a36b604174e3f274c4105/engine/namegen.mli
but I don't know it very well, I cannot help you more

**Comment by Tragicus** [comment]
Ok, thanks. I did something, hopefully it is sensible.

**Comment by proux01** [comment]
Note that since Coq 8.19 will never get the fixed hook, this PR is probably useless and superseeded by #596 (which will end up in master when it will be merged with coq-master to move to Coq 8.20).

**Pull request closed without merging**
