### PR TITLE
blind fix for windows path

### LINKED ISSUE #551: Issues building coq-elpi.1.19.3 on Windows (Coq Platform. cygwin MinGW cross)
I have issue sbuilding coq-elpi.1.19.3 in Coq Platform for Windows.

I added a dune patch which fixed most Windows build issues, but this remains.

The error message is:
```
OCAMLLIBDEP src/elpi_coercion_plugin.mlpack
COQDEP VFILES
FILL .merlin
CAMLOPT -c -for-pack Elpi_coercion_plugin src/coq_elpi_coercion_hook.ml
ocamlfind: Package `coq-elpi.elpi' not found
make[3]: *** [Makefile.coq:757: src/coq_elpi_coercion_hook.cmx] Error 2
make[2]: *** [Makefile.coq:409: all] Error 2
make[1]: *** [Makefile:15: build] Error 2
```

What I don't quite understand is how ocamlfind could possibly find a coq-elpi package before coq-elpi is installed.

I have:
```
$ ocamlfind list | grep elpi
elpi                (version: 1.17.4)
elpi.lexer_config   (version: 1.17.4)
elpi.parser         (version: 1.17.4)
elpi.trace          (version: n/a)
elpi.trace.ppx      (version: 1.17.4)
elpi.trace.runtime  (version: 1.17.4)
elpi.util           (version: 1.17.4)
```

Is there a mechanism that ocamlfind looks for packages in the local build folders?

### PR DESCRIPTION
**Pull request by gares**
Fix #551

### CODE REVIEW

**Comment by gares** [comment]
@Msoegtropimc @rtetley this is my fix for the platform, but since my CI is not testing windows I won't merge unless you confirm it is correct.

**Comment by gares** [comment]
CC @FissoreD , this should also go to the TC app

**Comment by gares** [comment]
done also for TC

**Comment by MSoegtropIMC** [comment]
@gares : I will test it on Windows now.

**Comment by MSoegtropIMC** [comment]
@gares: this doesn't work for me. I back ported the patch to 1.19.3 as follows:
```
From 13e76f10200077e6029c6c866d32a25fb0ae455a Mon Sep 17 00:00:00 2001
From: Michael Soegtrop <7895506+MSoegtropIMC@users.noreply.github.com>
Date: Sat, 25 Nov 2023 18:56:43 +0100
Subject: [PATCH] Back ported  blind fix for windows path #552 to latest
 release

---
 apps/coercion/Makefile.coq.local | 2 --
 1 file changed, 2 deletions(-)

diff --git a/apps/coercion/Makefile.coq.local b/apps/coercion/Makefile.coq.local
index f120308b..1101f4b2 100644
--- a/apps/coercion/Makefile.coq.local
+++ b/apps/coercion/Makefile.coq.local
@@ -1,3 +1 @@
 CAMLPKGS+= -package coq-elpi.elpi
-OCAMLPATH:=../../src/:$(OCAMLPATH)
-export OCAMLPATH
\ No newline at end of file
-- 
2.37.3
```
but the error is the same.

**Comment by gares** [comment]
The backport is wrong. You should use ; on windows, instead of : 

The backport does not set OCAMLPATH that is still needed

**Comment by MSoegtropIMC** [comment]
Sorry - not sure what I did there. I now tried to cut the piece for the existing file from your [diff](https://github.com/LPCIC/coq-elpi/commit/bb2c386c6f63a9f66375a5ca538b8c00a8c5594f.diff) like this:
```
diff --git a/apps/coercion/Makefile.coq.local b/apps/coercion/Makefile.coq.local
--- a/apps/coercion/Makefile.coq.local
+++ b/apps/coercion/Makefile.coq.local
@@ -1,3 +1,10 @@
 CAMLPKGS+= -package coq-elpi.elpi
-OCAMLPATH:=../../src/:$(OCAMLPATH)
+
+ifeq "$(shell which cygpath >/dev/null 2>&1)" ""
+OCAMLFINDSEP=:
+else
+OCAMLFINDSEP=;
+endif
+
+OCAMLPATH:=../../src/$(OCAMLFINDSEP)$(OCAMLPATH)
 export OCAMLPATH
\ No newline at end of file
```
but this doesn't work either. i double checked in the opam build folder that the patch is applied correctly. The error is:
```
# CAMLOPT -c -for-pack Elpi_coercion_plugin src/coq_elpi_coercion_hook.ml
# ocamlfind: Package `coq-elpi.elpi' not found
# make[3]: *** [Makefile.coq:757: src/coq_elpi_coercion_hook.cmx] Error 2
# make[2]: *** [Makefile.coq:409: all] Error 2
# make[1]: *** [Makefile:15: build] Error 2
# make[1]: Leaving directory '/home/Michael/.opam/CP.2023.11.0~8.18~test/.opam-switch/build/coq-elpi.1.19.3/apps/coercion'
# make: *** [Makefile:57: build-apps] Error 2
```
If you are out of ideas, I can add some debugging code to ocamlfind.

**Comment by gares** [comment]
I'd like to see the value of OCAMLPATH when ocamlfind is called.
Testing for cygpath is maybe suboptimal, but I had not better idea.

Also, I believe having to use different separators on windows and unix in ocamlfind is a bad choice.
I mean `c:\\path1:d:\\path2` may seem ambiguous, but IMO "paths" of length 1 can safely glued to the following one on windows. It won't always work, but it will always work in practice. Having to use a different separator is pushing on users the pain of OS detection.

**Comment by MSoegtropIMC** [comment]
> I mean c:\\path1:d:\\path2 may seem ambiguous, but IMO "paths" of length 1 can safely glued to the following one on windows. 

good point - I will try to implement this.

**Comment by MSoegtropIMC** [comment]
(I anyway need to patch ocamlfind in Coq Platform to make it installer relocatable - usually it isn't).

**Comment by MSoegtropIMC** [comment]
@gares: I added the last line (printf) in findlib.ml at:
```
  let env_search_path = 
    Fl_split.path
      (match env_ocamlpath with
	   Some x -> x
	 | None -> 
	     try Sys.getenv "OCAMLPATH" with Not_found -> "" 
      )
  in
  List.iter (Printf.eprintf "'%s'") env_search_path;  <<<< NEW
```
The output for some good cases:
```
CAMLC -a -o src/elpi_plugin.cma
'C:\bin\cygwin64_coq_platform\home\Michael\.opam\CP.2023.11.0~8.18~test\lib/coq\../coq-core\plugins/btauto'<many more coq folders in 4 repetitions>

COQDEP VFILES
'C:\bin\cygwin64_coq_platform\home\Michael\.opam\CP.2023.11.0~8.18~test\lib/coq\../coq-core\plugins/btauto'<many more coq folders in 4 repetitions>
FILL .merlin
'C:\bin\cygwin64_coq_platform\home\Michael\.opam\CP.2023.11.0~8.18~test\lib/coq\../coq-core\plugins/btauto'<many more coq folders in 4 repetitions>

CAMLC -a -o src/elpi_plugin.cma
'C:\bin\cygwin64_coq_platform\home\Michael\.opam\CP.2023.11.0~8.18~test\lib/coq\../coq-core\plugins/btauto'<many more coq folders in 4 repetitions>
(4x)

COQC theories/elpi.v
'src''C:\bin\cygwin64_coq_platform\home\Michael\.opam\CP.2023.11.0~8.18~test\lib/coq\../coq-core\plugins/btauto'<many more coq folders in 4 repetitions>

COQC theories/derive.v
'../../src''C:\bin\cygwin64_coq_platform\home\Michael\.opam\CP.2023.11.0~8.18~test\lib/coq\../coq-core\plugins/btauto'<many more coq folders in 4 repetitions>

COQC theories/assumption.v
'../../src''C:\bin\cygwin64_coq_platform\home\Michael\.opam\CP.2023.11.0~8.18~test\lib/coq\../coq-core\plugins/btauto'<many more coq folders in 4 repetitions>

```
The output from the end when it fails:
```
make[1]: Entering directory '/home/Michael/.opam/CP.2023.11.0~8.18~test/.opam-switch/build/coq-elpi.1.19.3/apps/coercion'
Using coq found in C:/bin/cygwin64_coq_platform/home/Michael/.opam/CP.2023.11.0~8.18~test/bin/, from COQBIN or PATH
Warning: ../../theories (used in -R or -Q) is not a subdirectory of the current directory

'C:\bin\cygwin64_coq_platform\home\Michael\.opam\CP.2023.11.0~8.18~test\lib/coq\../coq-core\plugins/btauto'<many more coq folders in 4 repetitions>
'../../src/:'COQPP src/coq_elpi_coercion_hook.mlg
CAMLDEP src/coq_elpi_coercion_hook.ml
'../../src/:'OCAMLLIBDEP src/elpi_coercion_plugin.mlpack
COQDEP VFILES
'C:\bin\cygwin64_coq_platform\home\Michael\.opam\CP.2023.11.0~8.18~test\lib/coq\../coq-core\plugins/btauto'<many more coq folders in 4 repetitions>
'../../src/:'FILL .merlin
'C:\bin\cygwin64_coq_platform\home\Michael\.opam\CP.2023.11.0~8.18~test\lib/coq\../coq-core\plugins/btauto'<many more coq folders in 4 repetitions>
'../../src/:../../src/:''C:\bin\cygwin64_coq_platform\home\Michael\.opam\CP.2023.11.0~8.18~test\lib/coq\../coq-core\plugins/btauto'<many more coq folders in 4 repetitions>
'../../src/:''C:\bin\cygwin64_coq_platform\home\Michael\.opam\CP.2023.11.0~8.18~test\lib/coq\../coq-core\plugins/btauto'<many more coq folders in 4 repetitions>
'../../src/:../../src/:''C:\bin\cygwin64_coq_platform\home\Michael\.opam\CP.2023.11.0~8.18~test\lib/coq\../coq-core\plugins/btauto'<many more coq folders in 4 repetitions>
'../../src/:../../src/:'CAMLOPT -c -for-pack Elpi_coercion_plugin src/coq_elpi_coercion_hook.ml
'../../src/:../../src/:'ocamlfind: Package `coq-elpi.elpi' not found
make[3]: *** [Makefile.coq:757: src/coq_elpi_coercion_hook.cmx] Error 2
make[2]: *** [Makefile.coq:409: all] Error 2
make[1]: *** [Makefile:15: build] Error 2
make[1]: Leaving directory '/home/Michael/.opam/CP.2023.11.0~8.18~test/.opam-switch/build/coq-elpi.1.19.3/apps/coercion'
make: *** [Makefile:57: build-apps] Error 2
```
==> apparently there is a place in make, where the :/; translation is not done

My current patch is:
```
diff --git a/apps/coercion/Makefile.coq.local b/apps/coercion/Makefile.coq.local
--- a/apps/coercion/Makefile.coq.local
+++ b/apps/coercion/Makefile.coq.local
@@ -1,3 +1,10 @@
 CAMLPKGS+= -package coq-elpi.elpi
-OCAMLPATH:=../../src/:$(OCAMLPATH)
+
+ifeq "$(shell which cygpath >/dev/null 2>&1)" ""
+OCAMLFINDSEP=:
+else
+OCAMLFINDSEP=;
+endif
+
+OCAMLPATH:=../../src/$(OCAMLFINDSEP)$(OCAMLPATH)
 export OCAMLPATH
\ No newline at end of file
```
So it should work for coercions, but it doesn't - I hadn't have time to look deeper into it.

**But no need for eaction - I try to implement your suggestion (tomorrow)**

**Comment by MSoegtropIMC** [comment]
@gares : FYI: I implemented your suggestion to also allow : as path list separator on Windows but bot split single letter paths (single character does not work because `.:<something` does happen). So I think you might want to remove this patch. The patch alone does not fix the issues with an unpatched ocamlfind.

**Pull request merged**
