### PR TITLE
Adapt to coq/coq#19346 (ComInductive flags)

### PR DESCRIPTION
**Pull request by SkySkimmer**

### CODE REVIEW

**Comment by SkySkimmer** [comment]
I let you add the optcomp stuff because I really don't want to deal with it.

**Comment by gares** [comment]
on it

**Review by gares — APPROVED** [review]

**Comment by ppedrot** [comment]
Please merge now. (For some reason I still don't have write rights to coq-elpi.)

**Comment by gares** [comment]
Damn, we should look into that.

**Comment by erikmd** [comment]
Hi @gares,
Given this overlay is not present in the latest release of coq-elpi, 2.2.1:
the [`mathcomp/mathcomp:2.2.0-coq-dev`](https://gitlab.inria.fr/math-comp/docker-mathcomp/-/pipelines/1006633) and [`mathcomp/mathcomp-dev:coq-dev`](https://gitlab.inria.fr/math-comp/math-comp/-/pipelines/1006630) FTBFS.

would it make sense to release a coq-elpi.2.2.1 compatible with coq-dev ?

otherwise, no worries, but I'll need to remove the `mathcomp/*:coq-dev ` images from Docker Hub.

**Comment by gares** [comment]
I can do another release, but a released version can only work on coq dev up to the day it was released, I'm not so sure I understand your request. For coq master you should track coq-elpi master

**Comment by erikmd** [comment]
Hi, thanks for your reply, to better explain my request:

1. mathcomp/mathcomp provides images of stable releases of mathcomp + coq-dev,
2. mathcomp/mathcomp-dev provides images of mathcomp master + coq-dev

it happens 1. and 2. don't compile anymore because in both cases, opam installs coq-hierarchy-builder.dev, which subsequently installs coq-elpi.2.2.1, which fails.

See the two logs:

* https://gitlab.inria.fr/math-comp/docker-mathcomp/-/jobs/4561637
* https://gitlab.inria.fr/math-comp/math-comp/-/jobs/4561638

I don't know what's the best solution, but note that this issue may occur again later on, given coq-elpi is a main dependency of mathcomp.

**Comment by SkySkimmer** [comment]
The solution is probably https://github.com/coq/opam/pull/3102

**Comment by erikmd** [comment]
Maybe, the opam constraints could induce that coq-hierarchy-builder.dev installs coq-elpi.dev, so that the merge of overlay could straightforwardly solve the issue in the docker-mathcomp builds? @gares, WDYT?

**Comment by gares** [comment]
> Maybe, the opam constraints could induce that coq-hierarchy-builder.dev installs `coq-elpi.dev`, so that the merge of overlay could straightforwardly solve the issue in the docker-mathcomp builds? @gares, WDYT?

I don't know how to do that, but if you do, then go ahead, it seems the right fix

**Comment by SkySkimmer** [comment]
There shouldn't be a need to change HB, only make the coq-elpi released version package stop claiming to be compatible with arbitrarily high coq versions when it's only compatible with coq versions that were already released when the coq-elpi was released.

**Comment by erikmd** [comment]
I agree with you, this should be enough.

(I restarted the mathcomp+coq-dev builds, hopefully the build/deployment will be OK now.)

**Pull request merged**
