### PR TITLE
[coq] Adapt to coq/coq#9165

### PR DESCRIPTION
**Pull request by ejgallego**

### CODE REVIEW

**Comment by ejgallego** [comment]
PR has been merged to Coq's master, please merge.

**Comment by vbgl** [comment]
Coq master and the 8.10 version have started diverging. A single version of this plug-in cannot be compatible with both.

Could the commit from this PR be also added to a new branch (say `coq-v8.10`) based on commit f59fadf9dcd2fcc765996e44265e446d3daf4303?

Thanks for your cooperation.

**Comment by gares** [comment]
New branch created, please test if it is OK

**Comment by vbgl** [comment]
The worked as expected. Thank you very much!

**Pull request merged**
