### PR TITLE
Adapt to https://github.com/coq/coq/pull/19216

### PR DESCRIPTION
**Pull request by proux01**
Adapt to https://github.com/coq/coq/pull/19216

### CODE REVIEW

**Review by gares — CHANGES_REQUESTED** [review]
optcomp

**Comment by proux01** [comment]
Indeed, not yet used to it, done.

**Comment by gares** [comment]
oh thanks, I would have done it myself.

**Review by gares — APPROVED** [review]

**Comment by proux01** [comment]
Upstream PR merged, please merge

**Pull request merged**
